MONSTER = 0
LOOTBOX = 1
BOSS = 2
MELEE = 3
RANGE = 4

stages = [
    [MONSTER,MONSTER,MONSTER,MONSTER,BOSS],
    [LOOTBOX,MONSTER,MONSTER,MONSTER,BOSS],
    [MONSTER,LOOTBOX,MONSTER,MONSTER,BOSS],
    [MONSTER,MONSTER,LOOTBOX,MONSTER,BOSS],
    [MONSTER,MONSTER,MONSTER,LOOTBOX,BOSS],
    [LOOTBOX,LOOTBOX,MONSTER,MONSTER,BOSS],
    [LOOTBOX,MONSTER,LOOTBOX,MONSTER,BOSS],
    [LOOTBOX,MONSTER,MONSTER,LOOTBOX,BOSS],
    [MONSTER,LOOTBOX,MONSTER,LOOTBOX,BOSS],
    [MONSTER,LOOTBOX,LOOTBOX,MONSTER,BOSS],
    [LOOTBOX,LOOTBOX,LOOTBOX,MONSTER,BOSS],
    [LOOTBOX,LOOTBOX,MONSTER,LOOTBOX,BOSS],
    [LOOTBOX,MONSTER,LOOTBOX,LOOTBOX,BOSS],
    [MONSTER,LOOTBOX,LOOTBOX,LOOTBOX,BOSS],
    [LOOTBOX,LOOTBOX,LOOTBOX,LOOTBOX,BOSS],

    
]

