MONSTER = 0
LOOTBOX = 1
BOSS = 2

stages = [
    [MONSTER,MONSTER,LOOTBOX,MONSTER,BOSS],
    [LOOTBOX,MONSTER,MONSTER,MONSTER,BOSS],
    [MONSTER,LOOTBOX,MONSTER,LOOTBOX,BOSS],
    [LOOTBOX,LOOTBOX,MONSTER,MONSTER,BOSS],
    [MONSTER,MONSTER,MONSTER,LOOTBOX,BOSS],
    [LOOTBOX,LOOTBOX,MONSTER,MONSTER,BOSS],
    
]

